#!/usr/bin/env node
// Reads node_modules/olum-icons/dist and writes:
//   src/data/icon-names.js  - names only, grouped by category (and style, where present) - for search
//   src/data/icons.js       - names mapped to svg markup, same grouping - for rendering
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST_DIR = path.join(__dirname, "..", "node_modules", "olum-icons", "dist");
const OUT_DIR = path.join(__dirname, "..", "src", "data");

const SVG_EXPORT_RE = /`([^`]*)`/;

const CATEGORIES = {
  lucide: { dir: "lucide" },
  heroicons: { styles: { outline: "heroicons/outline", solid: "heroicons/solid" } },
  fontawesome: { styles: { solid: "fontawesome/solid", regular: "fontawesome/regular", brands: "fontawesome/brands" } },
  olum: { dir: "." },
};

function readIconDir(dir) {
  const icons = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (file === "index.js" || !file.endsWith(".js")) continue;
    const filePath = path.join(dir, file);
    const content = fs.readFileSync(filePath, "utf8");
    const match = content.match(SVG_EXPORT_RE);
    if (!match) throw new Error(`Could not find an svg export in ${filePath}`);
    icons[file.slice(0, -3)] = match[1];
  }
  return icons;
}

function writeModule(fileName, data) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const filePath = path.join(OUT_DIR, fileName);
  fs.writeFileSync(filePath, `// Auto-generated by scripts/build-icons.mjs - do not edit by hand.\nexport default ${JSON.stringify(data, null, 2)};\n`);
  console.log(`Wrote ${path.relative(process.cwd(), filePath)}`);
}

const icons = {};
const names = {};

for (const [category, config] of Object.entries(CATEGORIES)) {
  if (config.styles) {
    icons[category] = {};
    names[category] = {};
    for (const [style, rel] of Object.entries(config.styles)) {
      const map = readIconDir(path.join(DIST_DIR, rel));
      icons[category][style] = map;
      names[category][style] = Object.keys(map);
    }
  } else {
    const map = readIconDir(path.join(DIST_DIR, config.dir));
    icons[category] = map;
    names[category] = Object.keys(map);
  }
}

writeModule("icon-names.js", names);
writeModule("icons.js", icons);
